# -*- coding: utf-8 -*-
"""searching&ranking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrGhuHTK3IwLEP7ZiLZghUent3dbgVI1
"""

"""
MODEL 2: Video Ranker
Independent file - Filters, ranks, and returns top N results
"""

import numpy as np
from typing import Dict, Any, List, Optional

class VideoRanker:
    def __init__(self):
        print("✅ Video Ranker initialized")

    def rank(self,
             rag_results: Dict[str, Any],
             filter_type: str = 'engagement',
             min_views: Optional[int] = None,
             min_likes: Optional[int] = None,
             min_engagement: Optional[float] = None,
             difficulty: Optional[str] = None,
             topic: Optional[str] = None,
             duration: Optional[str] = None) -> List[Dict]:
        """
        Filter and rank videos, return top N results

        filter_type options:
        - 'engagement': uses pre-calculated engagement score
        - 'like_ratio': uses like/view ratio
        - 'comments': most commented
        - 'recency': newest videos first
        - 'popularity': views + likes + comments
        - 'balanced': relevance + engagement
        """

        video_ids = rag_results['ids'][0]
        distances = rag_results['distances'][0]
        metadatas = rag_results['metadatas'][0]

        print(f"📊 Total videos received: {len(video_ids)}")

        scored_videos = []
        for vid, meta, dist in zip(video_ids, metadatas, distances):
            # Apply filters
            if min_views and meta.get('views', 0) < min_views:
                continue
            if min_likes and meta.get('likes', 0) < min_likes:
                continue
            if min_engagement and meta.get('engagement_score', 0) < min_engagement:
                continue
            if difficulty and meta.get('difficulty_level') != difficulty:
                continue
            if topic and meta.get('topic') != topic:
                continue
            if duration and meta.get('duration_category') != duration:
                continue

            # Calculate score based on filter_type
            relevance = 1 - dist
            engagement = meta.get('engagement_score', 0)
            like_ratio = meta.get('like_view_ratio', 0)
            comments = meta.get('comments_count', 0)
            views = meta.get('views', 0)
            likes = meta.get('likes', 0)
            year = meta.get('year', 2020)

            if filter_type == 'engagement':
                score = engagement
            elif filter_type == 'like_ratio':
                score = like_ratio
            elif filter_type == 'comments':
                score = np.log1p(comments)
            elif filter_type == 'recency':
                score = (year - 2020) / 5
            elif filter_type == 'popularity':
                score = (0.4 * np.log1p(views) + 0.4 * np.log1p(likes) + 0.2 * np.log1p(comments))
            elif filter_type == 'balanced':
                score = (0.3 * relevance + 0.7 * engagement)
            else:
                score = relevance

            scored_videos.append({
                'video_id': vid,
                'title': meta.get('title', 'Untitled'),
                'channel': meta.get('channel', 'Unknown'),
                'url': f"https://www.youtube.com/watch?v={vid}",
                'embed_url': f"https://www.youtube.com/embed/{vid}",
                'views': meta.get('views', 0),
                'likes': meta.get('likes', 0),
                'comments': meta.get('comments_count', 0),
                'duration': meta.get('duration_category', 'N/A'),
                'topic': meta.get('topic', 'N/A'),
                'difficulty': meta.get('difficulty_level', 'N/A'),
                'year': meta.get('year', 'N/A'),
                'like_ratio': meta.get('like_view_ratio', 0) * 100,
                'engagement': meta.get('engagement_score', 0) * 100,
                'score': score
            })

        scored_videos.sort(key=lambda x: x['score'], reverse=True)
        

        print(f"🎯 After filters: {len(scored_videos)} videos")

        return scored_videos

    def display_results(self, videos: List[Dict]):
        """Pretty print ranked results"""
        print("\n" + "="*70)
        print("🏆 TOP RESULTS")
        print("="*70)

        for i, v in enumerate(videos, 1):
            medal = "🥇" if i == 1 else "🥈" if i == 2 else "🥉" if i == 3 else f"{i}."
            print(f"\n{medal} {v['title']}")
            print(f"   🔗 {v['url']}")
            print(f"   👤 {v['channel']} | 📚 {v['topic']} | 📊 {v['difficulty']}")
            print(f"   📈 Views: {self._format_num(v['views'])} | 👍 Likes: {self._format_num(v['likes'])}")
            print(f"   ⭐ Score: {v['score']:.3f}")

    def _format_num(self, num):
        if num >= 1_000_000:
            return f"{num/1_000_000:.1f}M"
        elif num >= 1_000:
            return f"{num/1_000:.1f}K"
        return str(num)

# ========== STANDALONE USAGE ==========
if __name__ == "__main__":
    # Create sample RAG results (simulating input from Model 1)
    sample_videos = []
    for i in range(15):
        sample_videos.append({
            'title': f'Video Title {i+1}',
            'channel': f'Channel {i+1}',
            'views': 100000 * (i+1),
            'likes': 5000 * (i+1),
            'comments_count': 100 * (i+1),
            'duration_category': ['Short', 'Medium', 'Long'][i % 3],
            'year': 2020 + (i % 5),
            'topic': ['Gaming', 'Cooking', 'Tech', 'Travel', 'Fitness'][i % 5],
            'difficulty_level': ['Beginner', 'Intermediate', 'Advanced'][i % 3],
            'like_view_ratio': 0.01 + (i * 0.005),
            'engagement_score': 0.02 + (i * 0.003),
        })

    rag_results = {
        'ids': [[f'vid{i+1}' for i in range(15)]],
        'distances': [[0.1 + (i*0.02) for i in range(15)]],
        'metadatas': [sample_videos]
    }

    # Initialize ranker
    ranker = VideoRanker()

    # Get top 5 using popularity filter
    top_5 = ranker.rank(
        rag_results,
        filter_type='popularity',
    )

    # Display results
    ranker.display_results(top_5)

